name: Build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

      - name: Build docker image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          tags: glibc-builder:ci
          push: false

      - name: Build glibc
        run: docker run --rm --env GLIBC_VERSION --env STDOUT=1 glibc-builder:ci > glibc-bin-$GLIBC_VERSION-0-$(uname -m).tar.gz
        env:
          GLIBC_VERSION: 2.38

      - name: Build assets
        run: |
          docker run --platform linux/arm64 --env STDOUT=1 ghcr.io/harryzcy/glibc-builder:latest $GLIBC_VERSION /usr/glibc-compat > glibc-bin-$GLIBC_VERSION-0-aarch64.tar.gz
          docker run --platform linux/amd64 --env STDOUT=1 ghcr.io/harryzcy/glibc-builder:latest $GLIBC_VERSION /usr/glibc-compat > glibc-bin-$GLIBC_VERSION-0-x86_64.tar.gz
        env:
          GLIBC_VERSION: 2.38
