name: Build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          tags: glibc-builder:ci
          push: false

      - name: Build glibc
        run: docker run --rm --env GLIBC_VERSION --env STDOUT=1 glibc-builder:ci > glibc-bin-$GLIBC_VERSION-0-$(uname -m).tar.gz
        env:
          GLIBC_VERSION: 2.38
